### ISSUE TITLE
Unable to assign devices

### ISSUE THREAD

**Issue by hoavananh** [colocrossing/colocrossing-whmcs-plugin#1]
We were trying to assign a device to a test customer but unable to assign it from the Colocrossing Portal Addon and at the product detail page: http://prntscr.com/8k96kx
There is no device to assign there + Unassigned Services link is not clickable.
We are using WHMCS 6.0.2

**Comment by mattandre** [comment]
I have not seen anyone have that issue yet and I am unable to replicate it. I will need access to the admin side of your WHMCS to further investigate. Open a ticket in our portal system at portal.colocrossing.com so we may further assist you.

Regards,
Matt Andre
